(function(){'use strict';function g(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function l(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:g(a)};throw Error(String(a)+" is not an iterable or ArrayLike");};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=this||self;function p(a,b){a=a.split(".");for(var c=n,d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};function q(a){this.i="";this.j=[];this.h="";if(a)if(typeof a=="string")a:{this.i="";this.j=[];this.h="";var b=a.split(" "),c=b[0]=="";a="";for(var d=[],e=c?1:0;e<b.length;e++)if(b[e])a?d.push(b[e]):a=b[e];else break a;a&&(c?this.h=a:this.i=a,this.j=d)}else a:if(this.i="",this.j=[],this.h="",a){c=(b=a.getAttribute("data-gwd-group-def")||"")?[]:[a];for(a=a.parentElement;a&&!b;)a.hasAttribute("data-gwd-group")?c.push(a):b=a.getAttribute("data-gwd-group-def"),a=a.parentElement;c=c.reverse();a=!!b;d=c[0];
if(a||d.id){e=[];for(var f=a?0:1;f<c.length;f++){var h=c[f].getAttribute("data-gwd-grp-id");if(!h)break a;e.push(h)}this.i=a?"":d.id;this.j=e;this.h=b||""}}}function r(a,b){if(!a.h)return null;for(var c=b;c;){var d=c.getAttribute("data-gwd-group");if(d==a.h)break;c=d&&c!=b?null:c.parentElement}return c?t(a,c):null}
function t(a,b){for(var c=0;b&&c<a.j.length;c++){for(var d=b.querySelector('[data-gwd-grp-id="'+a.j[c]+'"]'),e=d?d.parentElement:null;d&&e&&e!=b;)e.hasAttribute("data-gwd-group")?d=null:e=e.parentElement;b=d}return b};function u(a){var b=new q(a);if(!b.i&&v)b=r(b,v);else a:{var c=document;if(b.h)var d=c.querySelector('[data-gwd-group-def="'+b.h+'"]');else if(b.i){if(d=c.getElementById(b.i),!d){var e=c.querySelector("gwd-pagedeck");e?typeof e.getElementById=="function"&&(d=e.getElementById(b.i)):b.i=="document.body"&&(d=c.body)}}else{b=null;break a}b=t(b,d)}if(!b)switch(a){case "document.body":b=document.body;break;case "document":b=document;break;case "window":b=window}return b}
p("gwd.actions.events.getElementById",u);p("gwd.actions.events.addHandler",function(a,b,c,d){var e=new q(a),f=e.h;if(f!==""){a=l(document.querySelectorAll("[data-gwd-group = "+f+"]"));f=a.next();var h;try{for(;!f.done;f=a.next()){var k=r(e,f.value);k&&(c.gwd_actualHandler||(c.gwd_actualHandler=w.bind(null,c)),k.addEventListener(b,c.gwd_actualHandler,d))}}finally{f&&!f.done&&(h=a.return)&&h.call(a)}}else(e=u(a))&&e.addEventListener(b,c,d)});
p("gwd.actions.events.removeHandler",function(a,b,c,d){var e=new q(a),f=e.h;if(f!==""){a=l(document.querySelectorAll("[data-gwd-group = "+f+"]"));f=a.next();var h;try{for(;!f.done;f=a.next()){var k=r(e,f.value);k&&c.gwd_actualHandler&&k.removeEventListener(b,c.gwd_actualHandler,d)}}finally{f&&!f.done&&(h=a.return)&&h.call(a)}}else(e=u(a))&&a[0]!=" "&&e.removeEventListener(b,c,d)});
p("gwd.actions.events.setInlineStyle",function(a,b){function c(m){var B=m.target;B.style.transition=d;B.removeEventListener(m.type,c,!1)}if((a=u(a))&&b){var d=a.style[a.style.transition!==void 0?"transition":"-webkit-transition"];b=l(b.split(/\s*;\s*/));var e=b.next(),f;try{for(;!e.done;e=b.next()){var h=e.value;if(h){var k=h.split(RegExp("[:](?![/]{2})"));k[1]=k[1]?k[1].trim():"";if(!k[0]||!k[1])return;a.style.setProperty(k[0],k[1])}}}finally{e&&!e.done&&(f=b.return)&&f.call(b)}a.addEventListener("transitionend",
c,!1);a.addEventListener("webkitTransitionEnd",c,!1)}});var v=null;function w(a,b){v=b.target;a.call(null,b)}function x(a){var b=a.target;if(b){var c=b.getAttribute("data-event-name");c&&(a.stopPropagation(),a=document.createEvent("CustomEvent"),a.initCustomEvent(c,!0,!0,null),b.dispatchEvent(a))}}p("gwd.actions.timeline.dispatchTimedEvent",x);
p("gwd.actions.timeline.captureAnimationEnd",function(a){if(a)for(var b=["animationend","webkitAnimationEnd"],c=0;c<b.length;c++)a.addEventListener(b[c],x,!0)});p("gwd.actions.timeline.releaseAnimationEnd",function(a){if(a)for(var b=["animationend","webkitAnimationEnd"],c=0;c<b.length;c++)a.removeEventListener(b[c],x,!0)});p("gwd.actions.timeline.pauseAnimationClassName","gwd-pause-animation");p("gwd.actions.timeline.CURRENT_LABEL_ANIMATION","data-gwd-current-label");
p("gwd.actions.timeline.pause",function(a){(a=u(a))&&a.classList&&a.classList.add("gwd-pause-animation")});function y(a){(a=u(a))&&a.classList&&a.classList.remove("gwd-pause-animation")}p("gwd.actions.timeline.play",y);p("gwd.actions.timeline.togglePlay",function(a){(a=u(a))&&a.classList&&a.classList.toggle("gwd-pause-animation")});
function z(a,b){var c=u(a);if(!(c&&c.classList&&a&&b))return null;var d=c.getAttribute("data-gwd-current-label");d&&(c.classList.remove(d),c.removeAttribute("data-gwd-current-label"));y(a);d==b&&c.setAttribute("gwd-reflow",c.offsetWidth);c.classList.add(b);c.setAttribute("data-gwd-current-label",b);return c}
function A(a,b){var c=a.getAttribute("data-gwd-animation-labels");a=new Map;c=l((c||"").split(";"));var d=c.next(),e;try{for(;!d.done;d=c.next()){var f=d.value;if(f){var h=f.split(","),k=h[0].trim(),m=parseInt(h[1],10);k&&!isNaN(m)&&a.set(k,{labelName:k,labelTime:m})}}}finally{d&&!d.done&&(e=c.return)&&e.call(c)}return a.has(b)?a.get(b).labelTime:-1}function C(a,b){if(a=z(a,b))if(b=A(a,b),b>=0){var c;(c=window.gwd.texteffects)==null||c.goToAndPlay(a,b)}}p("gwd.actions.timeline.gotoAndPlay",C);
p("gwd.actions.timeline.gotoAndPause",function(a,b){var c=u(a);if(!c||!c.classList)return!1;var d;z(a,b)&&(d=window.setTimeout(function(){c.classList.add("gwd-pause-animation")},40));a=A(c,b);if(a>=0){var e;(e=window.gwd.texteffects)==null||e.goToAndPause(c,a)}return!!d});p("gwd.actions.timeline.gotoAndPlayNTimes",function(a,b,c,d){var e=u(a);e.gwdGotoCounters=e.gwdGotoCounters||{};e=e.gwdGotoCounters;d=d+"_"+b+"_counter";typeof e[d]=="undefined"&&(e[d]=0);e[d]<c&&C(a,b);e[d]++});
p("gwd.actions.pageLayout.EVENT_ROTATE_PORTRAIT","rotatetoportrait");p("gwd.actions.pageLayout.EVENT_ROTATE_LANDSCAPE","rotatetolandscape");var D;function E(){var a=window.innerHeight>=window.innerWidth?1:2;if(D!=a){D=a;switch(a){case 1:var b="rotatetoportrait";break;case 2:b="rotatetolandscape"}a=document.createEvent("CustomEvent");a.initCustomEvent(b||"",!0,!0,null);document.body.dispatchEvent(a)}}
p("gwd.actions.pageLayout.initialize",function(){D=window.innerHeight>=window.innerWidth?1:2;window.addEventListener("resize",E,!0)});p("gwd.actions.tilt.EVENT_TILT","tilt");var F=NaN,G=NaN,H=NaN;
function I(a){function b(h){return!h&&h!=0}if(!(b(a.alpha)||b(a.beta)||b(a.gamma))){var c,d=(c=a.alpha)!=null?c:0,e;c=(e=a.beta)!=null?e:0;var f;a=(f=a.gamma)!=null?f:0;isNaN(F)?(F=d,G=c,H=a):(F-d)*(F-d)+(G-c)*(G-c)+(H-a)*(H-a)<1225||(F=d,G=c,H=a,f=document.createEvent("CustomEvent"),f.initCustomEvent("tilt",!0,!0,{alpha:d,beta:c,gamma:a}),document.body.dispatchEvent(f))}}p("gwd.actions.tilt.initialize",function(){window.addEventListener("deviceorientation",I,!0)});var J;
p("gwd.actions.deviceShake.initialize",function(){J||(J=new K,window.addEventListener("devicemotion",J.v,!1))});p("gwd.actions.deviceShake.dispose",function(){J&&window.removeEventListener("devicemotion",J.v,!1)});function K(){this.u=this.m=this.j=this.o=this.l=this.i=NaN;this.h=!1;this.v=this.A.bind(this)}
K.prototype.A=function(a){a=a.accelerationIncludingGravity;var b;this.j=(b=a.x)!=null?b:0;var c;this.m=(c=a.y)!=null?c:0;var d;this.u=(d=a.z)!=null?d:0;this.h||window.setTimeout(this.B.bind(this),200);this.h=!0};K.prototype.B=function(){var a=Math.abs(this.j-this.i),b=Math.abs(this.m-this.l),c=Math.abs(this.u-this.o);this.i=this.j;this.l=this.m;this.o=this.u;a+b+c>18?L(this):this.h=!1};
function L(a){var b=document.createEvent("CustomEvent");b.initCustomEvent("shake",!0,!0,null);document.body.dispatchEvent(b);M(a);window.setTimeout(function(){this.h=!1}.bind(a),1E3)}function M(a){a.i=NaN;a.l=NaN;a.o=NaN}p("gwd.actions.deviceShake.ShakeHandler",K);}).call(this);
gwd.actions.gwdGenericad=gwd.actions.gwdGenericad||{};gwd.actions.gwdGenericad.exit=function(receiver,url,opt_collapseOnExit,opt_pageId){gwd.actions.events.getElementById(receiver).exit(url,opt_collapseOnExit,opt_pageId)};